version: '3.8'

services:
  app:
    image: kabilan108/cv.kabilan108.com:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
