version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dist
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
