name: deploy to DO-kabilserv

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
   
    - name: docker meta
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: kabilan108/cv.kabilan108.com

    - name: log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: kabilan108/cv.kabilan108.com:latest
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: ssh deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_PRIVATE_KEY }}
        script: |
          cd /var/www/cv.kabilan108.com
          docker compose pull
          docker compose up -d
